(set-logic HORN)
(declare-fun |inv| (Int) Bool)
(assert (forall ((i Int) (ip Int)) (=> (= i 0) (inv i))))
(assert (forall ((i Int) (ip Int)) (=> (and (inv i) (< i 1000000) (= ip (+ i 1))) (inv ip))))
(assert (forall ((i Int) (ip Int)) (=> (and (>= i 1000000) (inv i)) (<= i 1000000))))
(check-sat)
(get-model)
